### ISSUE TITLE
Database Error 

### ISSUE THREAD

**Issue by MichelePipi** [MichelePipi/DisciplineX#1]
Upon server startup, the plugin is shut down with the following error:

[19:36:41 ERROR]: [DisciplineX] The plugin has made an error to connect to the MySQL Database and has been shut down.
Please check your configuration.
[19:36:41 WARN]: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
[19:36:41 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[19:36:41 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:113)
[19:36:41 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:861)
[19:36:41 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
[19:36:41 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:234)
[19:36:41 WARN]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:180)
[19:36:41 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
[19:36:41 WARN]:        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
[19:36:41 WARN]:        at DisciplineX-1.0-SNAPSHOT.jar//xyz.michelepip.disciplinex.api.db.DatabaseHandler.createConnection(DatabaseHandler.java:33)
[19:36:41 WARN]:        at DisciplineX-1.0-SNAPSHOT.jar//xyz.michelepip.disciplinex.api.db.DatabaseHandler.createPlayersTable(DatabaseHandler.java:64)
[19:36:41 WARN]:        at DisciplineX-1.0-SNAPSHOT.jar//xyz.michelepip.disciplinex.api.db.DatabaseHandler.setupDatabase(DatabaseHandler.java:46)
[19:36:41 WARN]:        at DisciplineX-1.0-SNAPSHOT.jar//xyz.michelepip.disciplinex.DisciplineX.onEnable(DisciplineX.java:27)
[19:36:41 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[19:36:41 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[19:36:41 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[19:36:41 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[19:36:41 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640)
[19:36:41 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589)
[19:36:41 WARN]:        at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:1132)
[19:36:41 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:1038)
[19:36:41 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:59)
[19:36:41 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)
[19:36:41 WARN]:        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1000)
[19:36:41 WARN]:        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:985)
[19:36:41 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:526)
[19:36:41 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
[19:36:41 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598)
[19:36:41 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[19:36:41 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[19:36:41 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

**Version 1.0-S2**

**Comment by MichelePipi** [comment]
Fixed in https://github.com/MichelePipi/DisciplineX/commit/5c7f4f19f1354409af4e1fcab9c643bdb0cf09da

Due to incorrect Database credentials. A more detailed error message is provided to the end-user.
